### ISSUE TITLE
Undefined ELIXIR_VERSION in Dockerfile

### ISSUE THREAD

**Issue by am-nimrah** [sheharyarn/cloudup.dev#10]
The Dockerfile currently references the ELIXIR_VERSION argument without defining it explicitly. To address this issue, please add the following line before the FROM statement in the Dockerfile:
ARG ELIXIR_VERSION=1.12
This ensures that the ELIXIR_VERSION argument is properly defined, preventing potential build errors.

**Comment by ahmadzahiddd** [comment]
Defining the MIX_ENV environment variable in the Dockerfile is crucial for ensuring the accurate configuration and execution of Elixir applications. Addressing the issue of an undefined MIX_ENV variable enhances the Dockerfile's completeness, allowing developers to specify the desired environment, such as "prod" or "dev." This correction not only aligns with Elixir best practices but also facilitates consistent and reliable builds across different deployment environments. By explicitly setting the MIX_ENV variable, the Dockerfile becomes more versatile, catering to diverse application deployment scenarios and contributing to a more robust and adaptable containerized Elixir application.

**Comment by ahmadzahiddd** [comment]
Defining the ELIXIR_VERSION variable in the Dockerfile is paramount for ensuring a controlled and version-specific Elixir runtime environment. By addressing the issue of an undefined ELIXIR_VERSION, the Dockerfile gains clarity and reliability in specifying the Elixir version required for the application. This correction aligns with best practices in containerized development, facilitating reproducible builds and minimizing compatibility concerns. Explicitly setting the ELIXIR_VERSION variable not only enhances the Dockerfile's robustness but also contributes to a more stable and maintainable containerized Elixir application, promoting a consistent development and deployment experience

**Comment by sheharyarn** [comment]
Same as #11.
