### ISSUE TITLE
Undefined MIX_ENV in Dockerfile

### ISSUE THREAD

**Issue by am-nimrah** [sheharyarn/cloudup.dev#11]
The Dockerfile references the MIX_ENV argument without an explicit definition. To resolve this issue, consider adding the following line before the FROM statement:
ARG MIX_ENV=prod
This ensures that the MIX_ENV argument is defined, providing a default value of 'prod' unless explicitly overridden during the build.

**Comment by ahmadzahiddd** [comment]
Defining the MIX_ENV environment variable in the Dockerfile is crucial for ensuring the accurate configuration and execution of Elixir applications. Addressing the issue of an undefined MIX_ENV variable enhances the Dockerfile's completeness, allowing developers to specify the desired environment, such as "prod" or "dev." This correction not only aligns with Elixir best practices but also facilitates consistent and reliable builds across different deployment environments. By explicitly setting the MIX_ENV variable, the Dockerfile becomes more versatile, catering to diverse application deployment scenarios and contributing to a more robust and adaptable containerized Elixir application.

**Comment by sheharyarn** [comment]
As mentioned in previous comments, the `dockerfile` files in the codebase are templates. In the UI, the user will see the `MIX_ENV` correctly defined and referenced in the rendered `Dockerfile`.
