### ISSUE TITLE
Incorrect ENV Variable Syntax in Dockerfile

### ISSUE THREAD

**Issue by am-nimrah** [sheharyarn/cloudup.dev#12]
In the second stage of the Dockerfile, the ENV APP_NAME @{APP_NAME} statement uses incorrect syntax for variable substitution. Please correct it to the following:
ENV APP_NAME ${APP_NAME}
This ensures that the APP_NAME environment variable is set properly using the correct syntax.

**Comment by ahmadzahiddd** [comment]
Correcting the syntax of ENV variables in the Dockerfile is a critical refinement for ensuring proper configuration and runtime behavior. By addressing the incorrect syntax, the Dockerfile becomes more reliable, preventing potential errors during the container build and execution phases. This correction aligns with best practices for Dockerfile development, promoting consistency and accuracy in setting environment variables. Ensuring the accurate syntax of ENV variables not only enhances the stability of the Docker image but also contributes to a more robust and error-resistant deployment process, improving the overall quality and reliability of the containerized application.

**Comment by sheharyarn** [comment]
The Dockerfile generator in Cloudup uses a special substitution/replacement strategy that's transparent to the end-user. This allows the user to configure rarely modified variables at run-time and see the changes reflected immediately.

See this for reference:

https://github.com/sheharyarn/cloudup.dev/blob/4d64bd8aa8158ae6ce599d37f1db818182ecbd0a/src/templates/Docker/VariantTemplate.js#L30-L42
