### ISSUE TITLE
Redundant WORKDIR in Dockerfile

### ISSUE THREAD

**Issue by am-nimrah** [sheharyarn/cloudup.dev#13]
In the first stage of the Dockerfile, the WORKDIR /build is set but not used later in the commands. Consider evaluating whether it is necessary or if it can be omitted to enhance clarity.

**Comment by ahmadzahiddd** [comment]
Eliminating the redundant WORKDIR in the Dockerfile is pivotal for maintaining a clean and efficient container build process. By removing unnecessary WORKDIR commands, the Dockerfile becomes more concise and readable, simplifying the understanding of the build context. This optimization not only reduces the complexity of the file but also ensures a more straightforward and predictable environment setup. Eliminating redundant WORKDIR commands aligns with best practices, streamlining the Dockerfile structure for improved maintainability and facilitating a more efficient development and deployment workflow.

**Comment by sheharyarn** [comment]
I'm assuming you're talking about the Dockerfile for Phoenix apps, as that's where we aare using `WORKDIR /build` in the first stage.

But this is used later when copying the compiled app in the final stage: 

https://github.com/sheharyarn/cloudup.dev/blob/f670749cb8d80e74de856d2998f50f273f75d2c9/content/docker/elixir/phoenix/dockerfile#L81


Please clarify if I misunderstood.
