### ISSUE TITLE
Hardcoded Start Command in Dockerfile

### ISSUE THREAD

**Issue by am-nimrah** [sheharyarn/cloudup.dev#14]
The Dockerfile has a hardcoded start command in the CMD instruction, using "bin/${APP_NAME}", "start". Please verify whether this is the intended start command or if it requires more flexibility. If flexibility is needed, consider adjusting the CMD instruction accordingly.

**Comment by sheharyarn** [comment]
I'm assuming you are referring to the Dockerfiles for Elixir/Phoenix applications.

Using `bin/app_name start` is the default command that's run and is the industry standard in Elixir. This will very rarely change, and if it does change, we can expect that the developer would be experienced enough to modify the Dockerfile according to their special requirements.
