### ISSUE TITLE
Add a SUBMIT button - UX Issue

### ISSUE THREAD

**Issue by imrtls00** [sheharyarn/cloudup.dev#16]
# The Issue:
The current user interface misses a submit button when using dropdowns, as it automatically submits the form when the user selects an item from the drop-down menu. This design overlooks the scenario where the user may want to change their selection before submission.

**Comment by imrtls00** [comment]
# Proposed Solution: 
Introduce a submit button alongside the dropdown menu to allow users the flexibility to finalize their selection only when they are ready to submit the form. This addition will enhance user experience and provide a more intuitive interface for the users.

**Comment by ahmadzahiddd** [comment]
Integrating a "SUBMIT" button is a crucial UX enhancement that can significantly improve user interaction within the application. This addition streamlines user workflows, providing a clear and intuitive action point for submitting information or completing tasks. The inclusion of a well-designed "SUBMIT" button enhances overall usability and contributes to a more seamless and satisfying user experience, aligning with established UX principles. This improvement not only ensures consistency in user interface elements but also promotes ease of use, making the application more accessible and user-friendly.

**Comment by Sagarr124** [comment]
I have submitted a PR for this issue. Thank you for mentioning.

**Comment by sheharyarn** [comment]
Thank you for your feedback! 🌟

I would not call this a UX issue. While I agree the most common behavior is to submit the form by clicking the submit button; the better UX is to immediately reflect changes for simple selections and scenarios, which we have done in this case.
