### ISSUE TITLE
X and GitHub Icons

### ISSUE THREAD

**Issue by AhsanTariqGill** [sheharyarn/cloudup.dev#21]
On the front page X and Github icons are not properly managed one looks like a rectangle and the other is like a circle. Also overall UI can be improved much better.

**Comment by ahmadzahiddd** [comment]
The addition of X and GitHub icons in the recent pull request is a positive step towards enhancing visual elements in the project. However, to ensure a cohesive user experience, it's essential to address a few aspects. First, strive for consistency in icon style and size, aligning with any existing patterns in the project. Consider accessibility by confirming the clarity of icons, including alternative text or tooltips for users with visual impairments. Harmonizing the icons with the project's color theme and providing documentation on their purpose and usage will contribute to a seamless integration. Additionally, exploring standardized icon libraries could promote a unified design language, fostering a more polished visual appearance across the application. Overall, these considerations aim to refine the user interface and contribute to a visually appealing and user-friendly project.

**Comment by sheharyarn** [comment]
Thank you for providing your feedback! 🌟


> On the front page X and Github icons are not properly managed one looks like a rectangle and the other is like a circle.

We're using official X and Github follow/star buttons. While I agree the design could be better, we cannot change the official button designs. However, a custom design would definitely look nicer, but it is not a high priority for the team.

If you would like to contribute by updating the buttons to use custom design, PRs are welcome!


> Also overall UI can be improved much better.

This comment is vague. If you have specific suggestions that provide a clear path on what items can be improved, please describe them in detail in a new issue.
