### ISSUE TITLE
Add university email option.

### ISSUE THREAD

**Issue by ahmadsabir786** [sheharyarn/cloudup.dev#22]
Please provide as linkedin provide verify option for university gmails as here should be apply.

**Comment by ahmadzahiddd** [comment]
What I Liked:

Recognizing the importance of providing a university email option, catering to a specific user demographic.
Suggestions/Concerns:

Ensure the implementation of the university email option complies with security and privacy standards.
Clearly communicate the benefits and eligibility criteria for users opting to use their university email.
Consider implementing a seamless verification process to validate university email addresses.
Collaborate with university IT departments or administrators to align the feature with institutional policies.
Reproducible Steps (if applicable):

Provide examples or scenarios where users would benefit from using their university email, showcasing the practicality of this addition.
Additional Context:

Consider user testing or surveys to gauge the interest and usability of the university email option among your target audience.
Document any legal or compliance considerations related to collecting and managing university email data.
Gratitude:

Thank you for addressing the specific needs of users with university email addresses. This addition has the potential to enhance user inclusivity and engagement.

**Comment by sheharyarn** [comment]
This project has nothing to do with Linkedin, universities, or Gmail.

If I'm misunderstanding, please clarify.
