### ISSUE TITLE
Improve Syntax and CMD Path in Elixir Basic Docker file

### ISSUE THREAD

**Issue by devv-abubakar** [sheharyarn/cloudup.dev#33]
The Elixir Basic Dockerfile could benefit from some enhancements:

1. Correcting the syntax in ENV variable substitution.
1. Adjusting the path in the CMD instruction.

**Comment by sheharyarn** [comment]
This issue is a duplicate of #12 and #14. Both of which have been addressed in their individual issues as invalid.
