### ISSUE TITLE
Add Loading State - UX Issue

### ISSUE THREAD

**Issue by imrtls00** [sheharyarn/cloudup.dev#9]
There should be a loading state on the home page when the user selects an item from dropdowns.

When a user selects an item from the dropdowns on the home page, there should be a loading state indicator to provide feedback and indicate that the content is being loaded. Currently, the lack of a loading state causes confusion for users as they are uncertain whether their selection was registered. This improvement will enhance the user experience and provide clear feedback during the data retrieval process.

**Comment by ahmadzahiddd** [comment]
Integrating a loading state is a pivotal enhancement to improve the user experience, ensuring a smoother and more responsive interaction within the application. By adding a loading state, users are provided with visual feedback during data retrieval or processing, offering a transparent and engaging experience. This proactive approach not only enhances usability but also reduces user frustration by clearly indicating that the system is actively working on a task. This improvement aligns with established UX principles, contributing to a more polished and user-friendly interface, fostering positive user engagement and satisfaction.

**Comment by sheharyarn** [comment]
This isn't a high-priority task for the team, but PRs are welcome!

**Comment by sheharyarn** [comment]
Resolved in 9cbe40b6e71c3417426bb83851094c66c73fe5cf.
